import Head from 'next/head'
import InputFilter from '../components/Keywords/InputFilter'
import SearchTable from '../components/searchTable/SearchTable'
import styles from '../styles/Home.module.css'
import StateProvider from '../globalState/Index'

const Home=()=>{
  return (
    <StateProvider>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet"></link>
      </Head>
      <InputFilter/>
      <SearchTable/>
    </div>
    </StateProvider>
  )
}

export default Home